paths: 
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags: 
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos correctamente
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del server, usualmente generado por una query defectuosa
    post:
      summary: Se agrega un producto
      tags:
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/addProduct' 
  /api/products/{pid}:
    get:
      summary: Obtiene un productos por su pid
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: El id del Producto a solicitar.
        schema:
          $type: String  
      responses:
        "200":
          description: El Producto fue obtenido correctamente
          content:
            application/json:
              schema: 
                $ref: '#components/schemas/Product' 
    put:
      summary: Se actualiza un producto en base un pid
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: El product id del usuario a actualizar
        schema: 
          type: sting
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/addProduct'
    delete:
      summary: Obtiene un productos por su pid
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: El id del Producto a solicitar.
        schema:
          $type: String  
      responses:
        "200":
          description: El Producto fue obtenido correctamente
          content:
            application/json:
              schema: 
                $ref: '#components/schemas/Product'
components:
  schemas: 
    Product: 
      type: object
      properties: 
        title:
          type: string
          description: El nombre del producto.
        description:
          type: string
          description: El descripcion del producto.
        thumbnail:
          type: string
          description: El url de la imagen.
        price:
          type: number
          description: El precio del producto.
        stock:
          type: number
          description: El stock del producto.
        code:
          type: string
          description: El codigo unico del producto.
        category:
          type: string
          description: La categoria del producto.
        status:
          type: string
          description: El estado del producto.
      example:
        title: Producto 7
        description: descripción 2
        thumbnail: 
        price: 500
        stock: 100
        code: 00019
        category: clothe
        status: trues
  requestBodies: 
    addProduct:
      type: object
      properties: 
        title:
          type: string
          description: El nombre del producto.
        description:
          type: string
          description: El descripcion del producto.
        thumbnail:
          type: string
          description: El url de la imagen.
        price:
          type: number
          description: El precio del producto.
        stock:
          type: number
          description: El stock del producto.
        code:
          type: string
          description: El codigo unico del producto.
        category:
          type: string
          description: La categoria del producto.
        status:
          type: string
          description: El estado del producto.
      example:
        title: Producto 7
        description: descripción 2
        thumbnail: 
        price: 500
        stock: 100
        code: 00019
        category: clothe
        status: trues


